services:
  db:
    build: .
    image: postgres-db:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: appdb
    ports:
      - "3000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U app -d appdb"]
      interval: 10s
      retries: 10
      start_period: 30m

volumes:
  pgdata: